### ISSUE TITLE
Qualisys and anybody,ERROR:Numerical value of StartVal is out of range

### ISSUE THREAD

**Issue by hhhzyax** [qualisys/paf-anybody-example#1]
I am using a sample project 'paf-anybody-example-main' with qualisys motion capture systems and anybody.After successfully collecting motion capture data, when I attempted to load 'main.any' located in the 'static' folder under IOR, an ERROR occurred. Below is the ERROR information:
`ERROR(SCR.EXP0) :   ForcePlates.any(16)  :     Defined at :   ForcePlateTypes.any(479)  :   UpdFunData  :  Error in evaluation. Please refer to the following error messages for details ...
ERROR(OBJ5) :   ForcePlates.any(16)  :     Defined at :   ForcePlateAutoDetection.any(375)  :   farr ( AnyFloatVar StartVal, AnyFloatVar StepVal, AnyIntVar ValCount ) : Error in argument no.1 : StartVal  :  Numerical value of StartVal is out of range :  [0.0000e+00..0.0000e+00]
`
The error position reported is this:
` AnyFloatVar tStart = C3D_OBJECT.Header.FirstFrameNo/C3D_OBJECT.Header.VideoFrameRate;
  AnyFloatVar tEnd =  (C3D_OBJECT.Header.LastFrameNo+1)/C3D_OBJECT.Header.VideoFrameRate;
  AnyInt NoAnalogData= (C3D_OBJECT.Header.LastFrameNo - C3D_OBJECT.Header.FirstFrameNo +1)*C3D_OBJECT.Header.NoAnalogSamplesPer3DFrame;
  AnyFloat Time= farr( tStart, (tEnd-tStart)/( NoAnalogData - 1) ,  NoAnalogData);
`
How to solve this problem?

**Comment by AndreyAkse** [comment]
Could you attach your data to be able to replicate? What type of force plates do you use?

**Comment by AndreyAkse** [comment]
Also an option to contact AnyBody support to fix issues with force plates script

**Comment by hhhzyax** [comment]
I have successfully solved this problem, which arose because I did not configure the force plate correctly in qualisys.

**Comment by AndreyAkse** [comment]
Great news :)
